/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.1
  Fuel-Core version: 0.40.0
*/

export { TestContract } from './TestContract';
export { TestContractFactory } from './TestContractFactory';
export { Src20 } from './Src20';
export { Src20Factory } from './Src20Factory';
