name: Publish to Github Pages

on:
  pull_request:
    types: [opened, synchronize, edited, closed, reopened]
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.7
          run_install: true

      - name: Build
        run: pnpm build:preview

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

      # - name: Download artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: production-files
      #     path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   publish_dir: ./dist
